### PR TITLE
Fix collecting of assumptions #19

### LINKED ISSUE #19: Tableau verdict is broken
Tableau verdict seems to always be “This tableau doesn't prove anything.”

The new encoding of assumptions (no reference instead of self-reference) has probably not been implemented in the code that computes the verdict yet.

### PR DESCRIPTION
**Pull request by MatejKomlossy**

### CODE REVIEW

File: src/Helpers/Helper.elm [hunk 1]
```diff
@@ -99,15 +99,10 @@ assumptions : Zipper.Zipper -> List (Signed Formula)
...
-            ((Zipper.zFirstRef z).up
-                |> Maybe.andThen
-                    (\x ->
-                        if x == 0 then
-                            Just ()
-
-                        else
-                            Nothing
-                    )
+            (if List.isEmpty ( Zipper.zNode z |> .references ) then
```
Comment (crnkjck) [inline src/Helpers/Helper.elm]: It’d be nicer to either simply apply the predicate to the list of references `List.isEmpty (Zipper.zNode z).references`, or use the “pipeline“ throughout `z |> Zipper.zNode |> .references |> List.isEmpty`.
